docs: Mention updating Helm Charts for the first time configuration
Substra/substra-documentation pull request #248
Opened 2022-12-28 14:24 UTC by jjerphan

Those steps might be needed in order to resolve the charts for `substra/orchestrator` and `substra/substra-backend`.

Signed-off-by: Julien Jerphanion <git@jjerphan.xyz>

cc @Fabien-GELUS, whom I mentioned this.

2023-01-02 15:47 UTC, ThibaultFy commented
Thanks for the PR! 
Just to answer for the contribution part, we are currently working on the contributing guide (cf [here](https://github.com/Substra/substra-documentation/pull/230) ). It will be available ASAP !

2023-01-02 16:03 UTC, jjerphan commented
Thanks, @ThibaultFy!

2023-01-05 13:43 UTC, guilhem-barthes commented
Hi @jjerphan, thanks for your submission! Would you have more context to share with us about this issue? We didn't manage to reproduce your problem.

2023-01-09 12:56 UTC, jjerphan commented
Hi @guilhem-barthes, charts were not found when I was running `skaffold` commands. The commands that I added makes the charts accessible.

I can't reproduce the error (because those charts now exist), but I might flush caches or so so that I can.

2023-01-18 13:00 UTC, jjerphan commented
@ThibaultFy and @guilhem-barthes: I offer no guaranty that I can reach the problem I was facing, yet I can try coming up with a reproducer for it ; would you be interested?

2023-01-18 15:22 UTC, ThibaultFy commented
Hi @jjerphan ! Thanks for proposing your help, but we are currently deploying Substra from scratch on several machine in order to reproduce the issue you pointed out. We'll be able to come back at you and work on your contribution very soon normally 😄 !

2023-01-26 10:04 UTC, guilhem-barthes requested changes
Hi @jjerphan, thanks for your your contribution and your patience. I am sorry we took so much time to consider and review this contribution, we had some internal deadlines to meet which slowed down this process. We are able to reproduce and to also notice that your changes where needed in a fresh install. 

As you can see in the suggested changes, we do not want to introduce the tools `pushd` and `popd` as it is not as well-known as `cd` and may create more confusion on first-time user. If you want me to apply the suggested changes, please let me know!

2023-01-26 10:04 UTC, guilhem-barthes commented on docs/source/contributing/getting-started.rst
> +      pushd substra-backend/charts/substra-backend/
```suggestion
      cd substra-backend/charts/substra-backend/
```

2023-01-26 10:04 UTC, guilhem-barthes commented on docs/source/contributing/getting-started.rst
> +      popd
```suggestion
      cd ../../../
```

2023-01-26 11:09 UTC, jjerphan commented
Hi @guilhem-barthes, no problem for the delay: I was not necessarily expecting a prompt response. :slightly_smiling_face: 

I have committed your suggestions to use `cd`.

2023-01-26 11:34 UTC, guilhem-barthes approved these changes

2023-01-26 11:34 UTC, merged