feat: add upgrade not for warning after release 0.38
Substra/substra-documentation pull request #423
Opened 2024-06-24 14:34 UTC by guilhem-barthes

Fixes FL-1606

2024-06-24 15:09 UTC, SdgJlbl approved these changes

2024-06-25 08:16 UTC, thbcmlowk requested changes
Thank for the fix! Some minor comment thought 🙏

2024-06-25 08:16 UTC, thbcmlowk commented on docs/source/how-to/deploying-substra/upgrade-notes.rst
> +   #. For the backend:
I think this is not intented?

<img width="714" alt="image" src="https://github.com/Substra/substra-documentation/assets/135698225/7ec81964-8d76-4559-9f92-1e29da34b70d">

---

```suggestion
#. Run the following commands

   #. For the backend:
```

2024-06-25 08:16 UTC, thbcmlowk commented on docs/source/how-to/deploying-substra/upgrade-notes.rst
> +   #. For the orchestrator, use the previous command replacing `POSTGRES_PASSWORD` and `POSTGRES_USER` by their value
```suggestion
   #. For the orchestrator, use the previous command replacing ``POSTGRES_PASSWORD`` and ``POSTGRES_USER`` by their value
```

2024-06-25 08:16 UTC, thbcmlowk commented on docs/source/how-to/deploying-substra/upgrade-notes.rst
> +   * Helm release (hereafter ``$POD_NAME``, can be obtained from ``kubectl get pods -n $NAMESPACE``)
I find it a bit strange to have the note when the warning is expected 
> you may get the following warning:

---

```suggestion
This version upgrades the integrated PostgreSQL databases chart. After this uprade, you may get the following warning:

.. code-block::

   WARNING: database "<db_name>" has a collation version mismatch                                                                                                                                                     │
   DETAIL:  The database was created using collation version 2.31, but the operating system provides version 2.36.                                                                                                        
   HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE <db_name> REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.

.. note::

   You need to apply the following command for the ``substra-backend`` and the ``orchestrator``
   
#. Gather required info:

   * Kubernetes namespace (here ``$NAMESPACE``)
   * Helm release (hereafter ``$POD_NAME``, can be obtained from ``kubectl get pods -n $NAMESPACE``)
```

2024-06-25 09:36 UTC, thbcmlowk commented on docs/source/how-to/deploying-substra/upgrade-notes.rst
> +.. code-block::
<img width="716" alt="image" src="https://github.com/Substra/substra-documentation/assets/135698225/b29bcca8-62f8-4d83-915b-1b0593fcf8e4">

---

```suggestion
This version upgrades the integrated PostgreSQL databases chart. After this uprade, you may get the following warning:

.. code-block::
```

2024-06-25 09:43 UTC, thbcmlowk commented on docs/source/how-to/deploying-substra/upgrade-notes.rst
> +   #. For the orchestrator, use the previous command replacing ``POSTGRES_PASSWORD`` and ``POSTGRES_USER`` by their value
Increment does not seem to work but I'm not sure I know how to fix it
<img width="700" alt="image" src="https://github.com/Substra/substra-documentation/assets/135698225/fc729f67-1457-4cde-a545-6a227fada732">

It's working [here](https://github.com/Substra/substra-documentation/blob/main/docs/source/how-to/deploying-substra/walkthrough/20-orchestrator-deployment.rst?plain=1#L70-L72) and looks the same to me 
 
---

```suggestion
   #. For the backend:

   .. code-block:: bash

      kubectl exec -n $NAMESPACE $POD_NAME -- sh -c 'PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER $POSTGRES_DATABASE -c "REINDEX DATABASE;" -c " ALTER DATABASE \"$POSTGRES_DATABASE\" REFRESH COLLATION VERSION;"'

   #. For the orchestrator, use the previous command replacing ``POSTGRES_PASSWORD`` and ``POSTGRES_USER`` by their value
```

2024-06-26 07:53 UTC, thbcmlowk approved these changes
LGTM, thanks for updating!

2024-06-28 12:00 UTC, merged